week6/src/main/java/domain/MeetingEntity.java
package domain;

import lombok.*;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.Set;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "meeting")
public class MeetingEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String topic;

    @Column(name = "start_date")
    private LocalDateTime startTime;

    @Column(name = "end_date")
    private LocalDateTime endTime;

    @OneToOne
    @JoinColumn(name = "meeting_location", referencedColumnName = "id")
    private MeetingLocation meetingLocation;

    @ManyToMany
    @JoinTable(
            name = "linking",
            joinColumns = @JoinColumn(name = "meeting_id"),
            inverseJoinColumns = @JoinColumn(name = "person_id")
    )
    private Set<PersonEntity> persons;
}

week6/src/main/java/domain/MeetingLocation.java
package domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "locations")
public class MeetingLocation {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    private String name;

    @Column(name = "class")
    private String locationClass;
}

week6/src/main/java/domain/PersonEntity.java
package domain;

import lombok.*;

import javax.persistence.*;
import java.util.Set;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "persons")
public class PersonEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "person_id")
    private int personId;
    private String name;

    @ManyToMany(mappedBy = "persons")
    private Set<MeetingEntity> meetings;
}

week6/src/main/java/domain/SearchRestrictions.java
package domain;

import lombok.Data;

import java.time.LocalDateTime;

@Data
public class SearchRestrictions {
    private boolean searchForTopic;
    private boolean searchForStartDate;
    private boolean searchForEndDate;
    private String searchTopic;
    private LocalDateTime searchStartDate;
    private LocalDateTime searchEndDate;
}

week6/src/main/java/controller/MeetingBackingBean.java
package controller;

import domain.MeetingEntity;
import domain.MeetingLocation;
import domain.PersonEntity;
import domain.SearchRestrictions;
import repositories.LocationRepository;
import repositories.MeetingRepository;
import repositories.PersonRepository;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@ManagedBean(name = "meetings")
@SessionScoped
public class MeetingBackingBean {
    private MeetingEntity newMeeting = new MeetingEntity(0, "", null, null, null, null);
    private List<String> selectedPersonsIds = new ArrayList<>();
    private int selectedMeetingId;
    private List<MeetingEntity> allMeetings;
    private List<PersonEntity> personEntities;
    private List<MeetingLocation> meetingLocations;
    private List<MeetingEntity> foundMeetings;
    private MeetingEntity editMeeting = new MeetingEntity(0, "", null, null, null, null);

    private MeetingRepository meetingRepository = new MeetingRepository();
    private PersonRepository personRepository = new PersonRepository();
    private LocationRepository locationRepository = new LocationRepository();

    private boolean searchForTopic;
    private boolean searchForStartDate;
    private boolean searchForEndDate;
    private boolean searchForLocation;
    private boolean searchForPerson;

    public List<MeetingEntity> getAllMeetings() {
        allMeetings = meetingRepository.getAllMeetings();
        return allMeetings;
    }

    public List<MeetingLocation> getAllLocations() {
        meetingLocations = locationRepository.getAllLocations();
        return meetingLocations;
    }

    public void createMeeting() {
        MeetingEntity meetingEntity = buildMeetingEntity();
        meetingRepository.createMeeting(meetingEntity);
    }

    private MeetingEntity buildMeetingEntity() {
        String meetingTopic = newMeeting.getTopic();
        LocalDateTime meetingStartDate = newMeeting.getStartTime();
        LocalDateTime meetingDuration = newMeeting.getEndTime();
        MeetingLocation meetingLocation = meetingLocations.stream()
                .filter(meetingLocationEntity -> meetingLocationEntity.getId() == selectedMeetingId)
                .findFirst().get();
        Set<PersonEntity> attendingPersons = personEntities.stream()
                .filter(personEntity -> selectedPersonsIds.contains(String.valueOf(personEntity.getPersonId())))
                .collect(Collectors.toSet());
        return new MeetingEntity(0, meetingTopic, meetingStartDate, meetingDuration, meetingLocation, attendingPersons);
    }

    public void updateMeeting() {
    }

    public List<PersonEntity> getAllPersons() {
        personEntities = personRepository.getAllPersons();
        return personEntities;
    }

    public List<String> getSelectedPersonsIds() {
        return selectedPersonsIds;
    }

    public void setSelectedPersonsIds(List<String> selectedPersonsIds) {
        this.selectedPersonsIds = selectedPersonsIds;
    }

    public int getSelectedMeetingId() {
        return selectedMeetingId;
    }

    public void setSelectedMeetingId(int selectedMeetingId) {
        this.selectedMeetingId = selectedMeetingId;
    }

    public MeetingEntity getNewMeeting() {
        return newMeeting;
    }

    public void setNewMeeting(MeetingEntity newMeeting) {
        this.newMeeting = newMeeting;
    }

    public MeetingEntity getEditMeeting() {
        return editMeeting;
    }

    public boolean isSearchForTopic() {
        return searchForTopic;
    }

    public void setSearchForTopic(boolean searchForTopic) {
        this.searchForTopic = searchForTopic;
    }

    public boolean isSearchForStartDate() {
        return searchForStartDate;
    }

    public void setSearchForStartDate(boolean searchForStartDate) {
        this.searchForStartDate = searchForStartDate;
    }

    public boolean isSearchForEndDate() {
        return searchForEndDate;
    }

    public void setSearchForEndDate(boolean searchForEndDate) {
        this.searchForEndDate = searchForEndDate;
    }

    public boolean isSearchForLocation() {
        return searchForLocation;
    }

    public void setSearchForLocation(boolean searchForLocation) {
        this.searchForLocation = searchForLocation;
    }

    public boolean isSearchForPerson() {
        return searchForPerson;
    }

    public void setSearchForPerson(boolean searchForPerson) {
        this.searchForPerson = searchForPerson;
    }

    public List<MeetingEntity> getFoundMeetings() {
        return foundMeetings;
    }

    public void setEditMeeting(MeetingEntity editMeeting) {
        try {
            this.editMeeting = editMeeting;
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }

    public void searchForMeetings() {
        SearchRestrictions searchRestrictions = buildSearchRestrictions();
        foundMeetings = meetingRepository.search(searchRestrictions);
    }

    private SearchRestrictions buildSearchRestrictions() {
        SearchRestrictions searchRestrictions = new SearchRestrictions();
        searchRestrictions.setSearchForTopic(searchForTopic);
        searchRestrictions.setSearchTopic(editMeeting.getTopic());
        searchRestrictions.setSearchForStartDate(searchForStartDate);
        searchRestrictions.setSearchStartDate(editMeeting.getStartTime());
        searchRestrictions.setSearchForEndDate(searchForEndDate);
        searchRestrictions.setSearchEndDate(editMeeting.getEndTime());
        return searchRestrictions;
    }

    public void getMeeting() {
        // TERRIBLE!!!
        this.getAllMeetings();
        for (MeetingEntity meetingEntity : allMeetings) {
            if (meetingEntity.getId() == selectedMeetingId) {
                editMeeting = meetingEntity;
                break;
            }
        }
    }
}

week6/src/main/java/controller/PersonBackingBean.java
package controller;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "person")
@SessionScoped
public class PersonBackingBean {
    private String personName;
    private boolean hasEnteredUserName;

    public void setPersonName(String personName) {
        this.personName = personName;
    }

    public String getPersonName() {
        return personName;
    }

    public boolean getHasEnteredUserName() {
        return hasEnteredUserName;
    }

    public void setHasEnteredUserName(boolean hasEnteredUserName) {
        this.hasEnteredUserName = hasEnteredUserName;
    }

    public void searchForMeetings() {
        hasEnteredUserName = true;
    }
}

week6/src/main/webapp/dataEdit.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
    <ui:composition template="/templates/page.xhtml">
        <ui:define name="header">
            <title>Meetings</title>
        </ui:define>

        <ui:define name="content">
            <h:form id="form">
                <h:panelGrid columns="2">
                    <h:outputLabel for="meetingTopicSelect" value="#{msg['MEETING_TOPIC']}"/>
                    <p:selectOneMenu id="meetingTopicSelect"
                                     value="#{meetings.selectedMeetingId}">
                        <f:selectItems value="#{meetings.allMeetings}" var="elem"
                                       itemLabel="#{elem.topic}" itemValue="#{elem.id}"/>
                    </p:selectOneMenu>
                    <h:commandButton value="#{msg['DATA_EDIT_GET_BUTTON']}" action="#{meetings.getMeeting}"/>
                </h:panelGrid>
            </h:form>

            <h:form id="editForm">
                <h:panelGrid columns="2">
                    <h:outputLabel for="topic" value="#{msg['MEETING_TOPIC']}: "/>
                    <h:inputText id="topic" value="#{meetings.editMeeting.topic}"
                                 style="font-weight:bold"/>

                    <h:outputLabel for="startTimeDatePicker" value="#{msg['MEETING_START_TIME']}"/>
                    <p:datePicker id="startTimeDatePicker"
                                  value="#{meetings.editMeeting.startTime}" showTime="true"
                                  required="true"/>

                    <h:outputLabel for="durationDatePicker" value="#{msg['MEETING_END_TIME']}"/>
                    <p:datePicker id="durationDatePicker"
                                  value="#{meetings.editMeeting.endTime}" showTime="true"/>

                    <h:outputLabel for="durationDatePicker" value="#{msg['MEETING_PERSONS']}"/>
                    <p:selectManyMenu id="personsSelect"
                                      value="#{meetings.selectedPersonsIds}" showCheckbox="true"
                                      required="true">
                        <f:selectItems value="#{meetings.allPersons}" var="elem"
                                       itemLabel="#{elem.name}" itemValue="#{elem.personId}"/>
                    </p:selectManyMenu>

                    <h:outputLabel for="locationSelect" value="#{msg['MEETING_LOCATION']}"/>
                    <p:selectOneMenu id="locationSelect"
                                     value="#{meetings.selectedMeetingId}">
                        <f:selectItems value="#{meetings.allLocations}" var="elem"
                                       itemLabel="#{elem.name}" itemValue="#{elem.id}"/>
                    </p:selectOneMenu>

                    <h:commandButton value="#{msg['DATA_EDIT_UPDATE_BUTTON']}" action="#{meetings.updateMeeting}"/>
                </h:panelGrid>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>

week6/src/main/webapp/dataView.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
    <ui:composition template="/templates/page.xhtml">
        <ui:define name="header">
            <title>Meetings</title>
        </ui:define>

        <ui:define name="content">
            <h:form id="form">
                <p:dataTable id="meetingsTreeTable" editable="true"
                             editMode="rowEdit" rowIndexVar="rowId"
                             value="#{meetings.allMeetings}" var="meetingEntity">
                    <f:facet name="header">Meetings</f:facet>

                    <p:column headerText="#{msg['MEETING_ID']}">
                        <h:outputText value="#{meetingEntity.id}"/>
                    </p:column>
                    <p:column headerText="#{msg['MEETING_TOPIC']}">
                        <h:outputText value="#{meetingEntity.topic}"/>
                    </p:column>
                    <p:column headerText="#{msg['MEETING_START_TIME']}">
                        <h:outputText value="#{meetingEntity.startTime}"/>
                    </p:column>
                    <p:column headerText="#{msg['MEETING_END_TIME']}">
                        <h:outputText value="#{meetingEntity.endTime}"/>
                    </p:column>
                    <p:column headerText="#{msg['MEETING_LOCATION']}">
                        <h:outputText converter="meetingLocationConverter" value="#{meetingEntity.meetingLocation}"/>
                    </p:column>
                </p:dataTable>

                <p:commandButton update=":form:meetingDialogPanel"
                                 oncomplete="PF('meetingEntity').show()" title="#{msg['DATAVIEW_CREATE_MEETING']}">
                    <f:setPropertyActionListener value="#{meetings.newMeeting}"
                                                 target="#{meetings.newMeeting}"/>
                </p:commandButton>

                <p:dialog id="createDialog" header="#{msg['DATAVIEW_CREATE_MEETING_DIALOG']}" showEffect="fade"
                          modal="true" resizable="true" widgetVar="meetingEntity">
                    <p:outputPanel id="meetingDialogPanel">
                        <p:panelGrid columns="2" columnClasses="label,value">
                            <h:outputLabel for="topic" value="#{msg['MEETING_TOPIC']}"/>
                            <h:inputText id="topic" value="#{meetings.newMeeting.topic}"
                                         style="font-weight:bold">
                                <f:validator validatorId="meetingTopicValidator" for="topic"/>
                            </h:inputText>

                            <h:outputLabel for="startTimeDatePicker" value="#{msg['MEETING_START_TIME']}"/>
                            <p:datePicker id="startTimeDatePicker"
                                          value="#{meetings.newMeeting.startTime}" showTime="true"
                                          required="true">
                            </p:datePicker>

                            <h:outputLabel for="durationDatePicker" value="#{msg['MEETING_END_TIME']}"/>
                            <p:datePicker id="durationDatePicker"
                                          value="#{meetings.newMeeting.endTime}" showTime="true">
                            </p:datePicker>

                            <h:outputLabel for="personsSelect" value="#{msg['MEETING_PERSONS']}"/>
                            <p:selectManyMenu id="personsSelect"
                                              value="#{meetings.selectedPersonsIds}" showCheckbox="true"
                                              required="true">
                                <f:selectItems value="#{meetings.allPersons}" var="elem"
                                               itemLabel="#{elem.name}" itemValue="#{elem.personId}"/>
                            </p:selectManyMenu>

                            <h:outputLabel for="locationSelect" value="#{msg['MEETING_LOCATION']}"/>
                            <p:selectOneMenu id="locationSelect"
                                             value="#{meetings.selectedMeetingId}">
                                <f:selectItems value="#{meetings.allLocations}" var="elem"
                                               itemLabel="#{elem.name}" itemValue="#{elem.id}"/>
                            </p:selectOneMenu>

                            <h:commandButton value="#{msg['DATAVIEW_CREATION_BUTTON']}"
                                             action="#{meetings.createMeeting}"/>
                        </p:panelGrid>
                    </p:outputPanel>
                </p:dialog>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>

week6/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
    <ui:composition template="/templates/page.xhtml">
        <ui:define name="header">
            <title>Main page</title>
        </ui:define>

        <ui:define name="content">
            <h:outputText value="#{msg['INDEX_MENU_HEADER']}"/>
            <br/>
            <h:button outcome="dataView" value="#{msg['INDEX_MEETINGS']}"/>
            <h:button outcome="dataEdit" value="#{msg['INDEX_EDIT']}"/>
            <h:button outcome="searchPage" value="#{msg['INDEX_SEARCH']}"/>
        </ui:define>
    </ui:composition>
</h:body>
</html>

week6/src/main/webapp/searchPage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:body>
    <ui:composition template="/templates/page.xhtml">
        <ui:define name="header">
            <title>Meetings</title>
        </ui:define>
        <ui:define name="content">
            <h:form id="search">
                <h:panelGrid columns="3">
                    <h:outputLabel for="topic" value="#{msg['MEETING_TOPIC']}: "/>
                    <h:inputText id="topic" value="#{meetings.editMeeting.topic}"
                                 style="font-weight:bold"/>
                    <h:selectBooleanCheckbox value="#{meetings.searchForTopic}"/>

                    <h:outputLabel for="startTimeDatePicker" value="#{msg['MEETING_START_TIME']}"/>
                    <p:datePicker id="startTimeDatePicker"
                                  value="#{meetings.editMeeting.startTime}" showTime="true"
                                  required="true"/>
                    <h:selectBooleanCheckbox value="#{meetings.searchForStartDate}"/>

                    <h:outputLabel for="durationDatePicker" value="#{msg['MEETING_END_TIME']}"/>
                    <p:datePicker id="durationDatePicker"
                                  value="#{meetings.editMeeting.endTime}" showTime="true"/>
                    <h:selectBooleanCheckbox value="#{meetings.searchForEndDate}"/>

                    <h:outputLabel for="durationDatePicker" value="#{msg['MEETING_PERSONS']}"/>
                    <h:commandButton value="#{msg['DATA_EDIT_GET_BUTTON']}" action="#{meetings.searchForMeetings}"/>
                </h:panelGrid>
            </h:form>

            <p:dataTable id="foundMeetingsTable" editable="true"
                         editMode="rowEdit" rowIndexVar="rowId"
                         value="#{meetings.foundMeetings}" var="meetingEntity">
                <f:facet name="header">Meetings</f:facet>

                <p:column headerText="#{msg['MEETING_ID']}">
                    <h:outputText value="#{meetingEntity.id}"/>
                </p:column>
                <p:column headerText="#{msg['MEETING_TOPIC']}">
                    <h:outputText value="#{meetingEntity.topic}"/>
                </p:column>
                <p:column headerText="#{msg['MEETING_START_TIME']}">
                    <h:outputText value="#{meetingEntity.startTime}"/>
                </p:column>
                <p:column headerText="#{msg['MEETING_END_TIME']}">
                    <h:outputText value="#{meetingEntity.endTime}"/>
                </p:column>
            </p:dataTable>
        </ui:define>
    </ui:composition>
</h:body>
</html>