Project/src/main/java/domain/HouseOffer.java
package domain;

import constants.SellerType;

public class HouseOffer {
    private int roomsNumber;
    private SellerType sellerType;
    private int price;
    private int floorNumber;
}

Project/src/main/java/domain/HouseOfferEntity.java
package domain;

import lombok.Data;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

@Entity
@Data
@Table(name = "house_prices")
public class HouseOfferEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String id;

    @NotNull
    private int price;

    @NotNull
    private String location;

    @Column(name = "floor_number")
    @NotNull
    private int floorNumber;

    @Column(name = "rooms")
    @NotNull
    private int roomsNumber;

    @Column(name = "surface_sq_meters")
    @NotNull
    private int surfaceArea;

    @Column(name = "construction_year")
    @NotNull
    private int constructionYear;
}

Project/src/main/java/domain/JobEntity.java
package domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Data
@Table(name = "jobs")
@AllArgsConstructor
@NoArgsConstructor
public class JobEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "job_id")
    private Integer id;

    @Column(name = "started")
    private LocalDateTime startedDateTime;

    @Column(name = "finished")
    private LocalDateTime endedDateTime;

    @OneToOne
    @JoinColumn(name = "job_status", referencedColumnName = "job_status_id")
    private JobStatusEntity status;

    @OneToOne
    @JoinColumn(name = "job_type", referencedColumnName = "job_type_id")
    private JobTypeEntity type;

    private Integer delay;
}

Project/src/main/java/domain/JobStatusEntity.java
package domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Entity
@Table(name = "job_status")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class JobStatusEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "job_status_id")
    private Integer id;

    @Column(name = "status_name")
    private String status;
}

Project/src/main/java/domain/JobTypeEntity.java
package domain;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;

@Entity
@Table(name = "job_type")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class JobTypeEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "job_type_id")
    private Integer id;

    @Column(name = "type_name")
    private String type;
}

Project/src/main/java/model/CityNeighbourhoodMapping.java
package model;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
public class CityNeighbourhoodMapping {
    private String neighbourhoodName;
    private int rank;
}

Project/src/main/java/controller/HouseOffersBackingBean.java
package controller;

import domain.HouseOfferEntity;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import repositories.HouseOfferRepository;

import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.List;

@Named("houseOffersBackingBean")
@ApplicationScoped
public class HouseOffersBackingBean {
    public static final String CSV_MEDIA_TYPE = "text/csv";
    private static final String PYTHON_TRAINING_SCRIPT_PATH = "C:\\Users\\i_dre\\PycharmProjects\\pythonProject3";
    private static final String HOUSE_OFFERS_CSV_FILENAME = "data.csv";
    @EJB
    private HouseOfferRepository houseOfferRepository;

    private List<HouseOfferEntity> houseOffers;

    public HouseOfferRepository getHouseOfferRepository() {
        return houseOfferRepository;
    }

    public List<HouseOfferEntity> getHouseOffers() {
        houseOffers = houseOfferRepository.findAll();
        return houseOffers;
    }

    public StreamedContent getCsvFile() {
        return DefaultStreamedContent.builder()
                .name(HOUSE_OFFERS_CSV_FILENAME)
                .contentType(CSV_MEDIA_TYPE)
                .stream(() -> {
                    try {
                        return new FileInputStream(PYTHON_TRAINING_SCRIPT_PATH + File.separator + HOUSE_OFFERS_CSV_FILENAME);
                    } catch (FileNotFoundException e) {
                        e.printStackTrace();
                    }
                    return null;
                })
                .build();
    }
}

Project/src/main/java/controller/JobBackingBean.java
package controller;

import domain.JobEntity;
import domain.JobStatusEntity;
import domain.JobTypeEntity;
import lombok.Data;
import repositories.JobRepository;
import repositories.JobStatusRepository;
import repositories.JobTypeRepository;
import service.SchedulingService;

import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import java.time.LocalDateTime;
import java.util.List;

@Data
@Named("jobsBackingBean")
@ApplicationScoped
public class JobBackingBean {

    private static final int DEFAULT_DELAY_FOR_TRAINING_JOB = 0;
    private static final String SCRAPE_JOB_NAME = "Scrape";

    private String jobType;
    private String delay;
    private String city;

    @EJB
    private JobRepository jobRepository;

    @EJB
    private JobStatusRepository jobStatusRepository;

    @EJB
    private JobTypeRepository jobTypeRepository;

    @EJB
    private SchedulingService schedulingService;

    private List<JobEntity> jobEntities;
    private List<JobStatusEntity> jobStatusEntities;
    private List<JobTypeEntity> jobTypeEntities;

    public void addNewJob() {
        JobEntity job = createJobEntity();
        jobRepository.createJob(job);
        schedulingService.addJob(job);
    }

    public List<JobEntity> getJobEntities() {
        return jobRepository.findAll();
    }

    private JobEntity createJobEntity() {
        LocalDateTime now = LocalDateTime.now();
        jobStatusEntities = jobStatusRepository.getAllEntities();
        jobTypeEntities = jobTypeRepository.getAllEntities();
        JobStatusEntity queuedStatus = jobStatusEntities.get(0);
        JobTypeEntity jobTypeManagedEntity = jobType.equals(SCRAPE_JOB_NAME) ? jobTypeEntities.get(0) : jobTypeEntities.get(1);
        int parsedDelay = jobType.equals(SCRAPE_JOB_NAME) ? Integer.parseInt(delay) : DEFAULT_DELAY_FOR_TRAINING_JOB;
        return new JobEntity(null, now, null, queuedStatus, jobTypeManagedEntity, parsedDelay);
    }
}

Project/src/main/java/controller/PredictionBackingBean.java
package controller;

import lombok.Data;
import model.CityNeighbourhoodMapping;
import org.apache.commons.exec.CommandLine;
import org.apache.commons.exec.DefaultExecutor;
import org.apache.commons.exec.Executor;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Data
@Named("prediction")
@ApplicationScoped
public class PredictionBackingBean {
    private static final String PYTHON_TRAINING_SCRIPT_PATH = "C:\\Users\\i_dre\\PycharmProjects\\pythonProject3";
    private static final int TRAIN_JOB_SCRIPT_SUCCESS_RETURN_VALUE = 0;
    private static final String TRAIN_JOB_SCRIPT_TEMPLATE = "python %s";
    private static final String PYTHON_SCRIPT_NAME = "predict.py";
    private static final String PYTHON_SCRIPT_OUTPUT_FILE_NAME = "prediction.txt";
    private static final String CITY_NEIGHBOURHOOD_MAPPINGS_FILE_NAME = "ranks_mappings.txt";

    private int area;
    private int floorNumber;
    private int rooms;
    private int year;
    private int location;
    private double predictedPrice;
    private List<CityNeighbourhoodMapping> cityNeighbourhoodMappings;

    public void predictPrice() throws IOException {
        predictedPrice = getPricePrediction();
    }

    public List<CityNeighbourhoodMapping> getCityNeighbourhoodMappings() {
        List<String> cityNeighbourHoodRawFileMappings = readCityNeighbourhoodMappingsFileContent();
        return mapToCityNeighbourhood(cityNeighbourHoodRawFileMappings);
    }

    private List<CityNeighbourhoodMapping> mapToCityNeighbourhood(List<String> rawFileLines) {
        return rawFileLines.stream().map(this::extractCityNeighbourhoodDataFromRawFileLine).collect(Collectors.toList());
    }

    private CityNeighbourhoodMapping extractCityNeighbourhoodDataFromRawFileLine(String line) {
        String[] tokens = line.split(" ");
        String neighbourhoodName = getNeighbourhoodName(tokens);
        int assignedRank = Integer.parseInt(tokens[tokens.length - 1]);
        return new CityNeighbourhoodMapping(neighbourhoodName, assignedRank);
    }

    private String getNeighbourhoodName(String[] tokens) {
        StringBuilder stringBuilder = new StringBuilder();
        for (int i = 0, len = tokens.length; i < len - 1; i++) {
            stringBuilder.append(tokens[i]).append(" ");
        }
        return stringBuilder.toString();
    }

    private List<String> readCityNeighbourhoodMappingsFileContent() {
        try {
            Path cityNeighbourhoodMappingsFilePath = Paths.get(PYTHON_TRAINING_SCRIPT_PATH, CITY_NEIGHBOURHOOD_MAPPINGS_FILE_NAME);
            return Files.readAllLines(cityNeighbourhoodMappingsFilePath);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return new ArrayList<>();
    }

    private double getPricePrediction() throws IOException {
        String command = getPythonRunCommand();
        return runPythonPredictionScript(command);
    }

    private double runPythonPredictionScript(String command) throws IOException {
        CommandLine commandLine = CommandLine.parse(command);
        addCommandLineArguments(commandLine);
        executeScript(commandLine);
        return getScriptOutput();
    }

    private double executeScript(CommandLine commandLine) throws IOException {
        Executor defaultExecutor = getScriptExecutor();
        defaultExecutor.execute(commandLine);
        return getScriptOutput();
    }

    private double getScriptOutput() throws IOException {
        List<String> lines = Files.readAllLines(Paths.get(PYTHON_TRAINING_SCRIPT_PATH + File.separator + PYTHON_SCRIPT_OUTPUT_FILE_NAME));
        return Double.parseDouble(lines.get(0));
    }

    private Executor getScriptExecutor() {
        DefaultExecutor defaultExecutor = new DefaultExecutor();
        defaultExecutor.setExitValue(TRAIN_JOB_SCRIPT_SUCCESS_RETURN_VALUE);
        return defaultExecutor;
    }

    private void addCommandLineArguments(CommandLine commandLine) {
        commandLine.addArgument(String.valueOf(year));
        commandLine.addArgument(String.valueOf(rooms));
        commandLine.addArgument(String.valueOf(floorNumber));
        commandLine.addArgument(String.valueOf(area));
        commandLine.addArgument(String.valueOf(location));
    }

    private String getPythonRunCommand() {
        String scriptPath = PYTHON_TRAINING_SCRIPT_PATH + File.separator + PYTHON_SCRIPT_NAME;
        return String.format(TRAIN_JOB_SCRIPT_TEMPLATE, scriptPath);
    }
}

Project/src/main/webapp/dashboard.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<h:head>

</h:head>
<ui:composition template="templates/page.xhtml">
</ui:composition>
</html>

Project/src/main/webapp/data.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<ui:composition template="templates/page.xhtml">
    <ui:define name="content">
        <p:dataTable value="#{houseOffersBackingBean.houseOffers}"
                     paginator="true" rows="20"
                     widgetVar="houseOffersDataTable" var="houseOfferEntity">
            <p:column headerText="Offer id">
                <h:outputText value="#{houseOfferEntity.getId()}"/>
            </p:column>
            <p:column headerText="Floor number">
                <h:outputText value="#{houseOfferEntity.getFloorNumber()}"/>
            </p:column>
            <p:column headerText="Construction year">
                <h:outputText value="#{houseOfferEntity.getConstructionYear()}"/>
            </p:column>
            <p:column headerText="Location">
                <h:outputText value="#{houseOfferEntity.getLocation()}"/>
            </p:column>
            <p:column headerText="Price">
                <h:outputText value="#{houseOfferEntity.getPrice()}"/>
            </p:column>
            <p:column headerText="Rooms Number">
                <h:outputText value="#{houseOfferEntity.getRoomsNumber()}"/>
            </p:column>
            <p:column headerText="Area">
                <h:outputText value="#{houseOfferEntity.getSurfaceArea()}"/>
            </p:column>
        </p:dataTable>

        <h:form id="downloadForm">
            <p:commandButton value="Download CSV" ajax="false" onclick="PrimeFaces.monitorDownload(start, stop);"
                             icon="pi pi-arrow-down">
                <p:fileDownload value="#{houseOffersBackingBean.csvFile}"/>
            </p:commandButton>
        </h:form>
    </ui:define>
</ui:composition>
</html>

Project/src/main/webapp/jobs.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<ui:composition template="templates/page.xhtml">
    <ui:define name="content">
        <h:form id="form">
            <p:dataTable value="#{jobsBackingBean.jobEntities}" widgetVar="jobsDataTable" var="jobEntity">
                <p:column headerText="Job ID">
                    <h:outputText value="#{jobEntity.getId()}"/>
                </p:column>
                <p:column headerText="Type">
                    <h:outputText value="#{jobEntity.getType().type}"/>
                </p:column>
                <p:column headerText="Status">
                    <h:outputText value="#{jobEntity.getStatus().status}"/>
                </p:column>
                <p:column headerText="Started">
                    <h:outputText value="#{jobEntity.getStartedDateTime()}"/>
                </p:column>
                <p:column headerText="Ended">
                    <h:outputText value="#{jobEntity.getEndedDateTime()}"/>
                </p:column>
                <p:column headerText="Delay">
                    <h:outputText value="#{jobEntity.getDelay()}"/>
                </p:column>
            </p:dataTable>
            <p:commandButton value="Add" update=":form:jobsDataTable" type="button" onclick="PF('jobDialog').show();">
            </p:commandButton>

            <p:dialog id="addJobDialog" header="Add" widgetVar="jobDialog" showEffect="fade" modal="true"
                      resizable="true">
                <p:outputPanel id="addJobDialogPanel">
                    <p:panelGrid id="jobDetailsPanel" columns="2">
                        <p:outputLabel for="type" value="Job type"/>
                        <p:selectOneListbox id="type" value="#{jobsBackingBean.jobType}">
                            <f:selectItem itemLabel="Scrape" itemValue="Scrape"/>
                            <f:selectItem itemLabel="Train" itemValue="Train"/>
                        </p:selectOneListbox>
                        <p:outputLabel for="delay" value="Delay"/>
                        <p:inputText id="delay" value="#{jobsBackingBean.delay}"
                                     placeholder="How many seconds to wait between consecurive delays"/>
                        <p:commandButton value="Add" action="#{jobsBackingBean.addNewJob}"
                                         onclick="PF('jobDialog').hide();"
                                         update="@form"/>
                    </p:panelGrid>
                </p:outputPanel>
            </p:dialog>
        </h:form>
    </ui:define>
</ui:composition>
</html>

Project/src/main/webapp/prediction.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" xmlns:f="http://java.sun.com/jsf/core">
<ui:composition template="templates/page.xhtml">
    <ui:define name="content">
        <h:form id="predictionForm">
            <p:panelGrid columns="2">
                <p:outputLabel for="location" value="Location"/>
                <p:selectOneMenu id="location" value="#{prediction.location}">
                    <f:selectItems value="#{prediction.cityNeighbourhoodMappings}" var="cityNeightbourhoodMapping"
                                   itemValue="#{cityNeightbourhoodMapping.rank}"
                                   itemLabel="#{cityNeightbourhoodMapping.neighbourhoodName}"/>
                </p:selectOneMenu>
                <p:outputLabel for="rooms" value="Rooms"/>
                <p:inputText id="rooms" value="#{prediction.rooms}"/>
                <p:outputLabel for="area" value="Area"/>
                <p:inputText id="area" value="#{prediction.area}"/>
                <p:outputLabel for="floor" value="Floor number"/>
                <p:inputText id="floor" value="#{prediction.floorNumber}"/>
                <p:outputLabel for="year" value="Construction year"/>
                <p:inputText id="year" value="#{prediction.year}"/>
                <p:commandButton value="Predict price" action="#{prediction.predictPrice()}" update="@form"/>
            </p:panelGrid>
            <h:outputText value="Predicted price #{prediction.predictedPrice}"/>
        </h:form>
    </ui:define>
</ui:composition>
</html>

Project/src/main/webapp/scraping.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<ui:composition template="templates/page.xhtml">
    <ui:define name="content">
        <h:form id="form">
            <p:dataTable value="#{jobsBackingBean.jobEntities}" widgetVar="jobsDataTable" var="jobEntity">
                <p:column headerText="Job ID">
                    <h:outputText value="#{jobEntity.getId()}"/>
                </p:column>
                <p:column headerText="Type">
                    <h:outputText value="#{jobEntity.getType().type}"/>
                </p:column>
                <p:column headerText="Status">
                    <h:outputText value="#{jobEntity.getStatus().status}"/>
                </p:column>
                <p:column headerText="Started">
                    <h:outputText value="#{jobEntity.getStartedDateTime()}"/>
                </p:column>
                <p:column headerText="Ended">
                    <h:outputText value="#{jobEntity.getEndedDateTime()}"/>
                </p:column>
                <p:column headerText="Delay">
                    <h:outputText value="#{jobEntity.getDelay()}"/>
                </p:column>
            </p:dataTable>
            <p:commandButton value="Add" update=":form:jobsDataTable" type="button" onclick="PF('jobDialog').show();">
            </p:commandButton>

            <p:dialog id="addJobDialog" header="Add" widgetVar="jobDialog" showEffect="fade" modal="true"
                      resizable="true">
                <p:outputPanel id="addJobDialogPanel">
                    <p:panelGrid id="jobDetailsPanel" columns="2">
                        <p:outputLabel for="type" value="Job type"/>
                        <p:selectOneListbox id="type" value="#{jobsBackingBean.jobType}">
                            <f:selectItem itemLabel="Scrape" itemValue="Scrape"/>
                            <f:selectItem itemLabel="Train" itemValue="Train"/>
                        </p:selectOneListbox>
                        <p:outputLabel for="delay" value="Delay"/>
                        <p:inputText id="delay" value="#{jobsBackingBean.delay}"
                                     placeholder="How many seconds to wait between consecurive delays"/>
                        <p:outputLabel for="city" value="City"/>
                        <p:selectOneListbox id="city" value="#{jobsBackingBean.city}">
                            <f:selectItem itemLabel="iasi" itemValue="Iasi"/>
                            <f:selectItem itemLabel="cluj" itemValue="Cluj"/>
                            <f:selectItem itemLabel="bucuresti" itemValue="Bucuresti"/>
                        </p:selectOneListbox>
                        <p:commandButton value="Add" action="#{jobsBackingBean.addNewJob}"
                                         onclick="PF('jobDialog').hide();"/>
                    </p:panelGrid>
                </p:outputPanel>
            </p:dialog>
        </h:form>
    </ui:define>
</ui:composition>
</html>